name: clima
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  geolocator: ^14.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: "Spartan MB"
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900

# Launcher icons (use the same 1024x1024 PNG for all platforms)
flutter_launcher_icons:
  image_path: assets/icon/app_icon.png
  ios: true
  remove_alpha_ios: true
  android: true
  windows:
    generate: true
    image_path: assets/icon/app_icon.png
    icon_size: 256

# Native splash (Android/iOS); reuses the same image
flutter_native_splash:
  android: true
  ios: true
  web: false

  # Background color behind the centered image
  color: "#2563EB"
  # Optional dark-mode background
  color_dark: "#0B1F4B"

  # Center image (same as launcher icon)
  image: assets/icon/app_icon.png
  image_dark: assets/icon/app_icon.png

  # Android 12+ specific config
  android_12:
    image: assets/icon/app_icon.png
    icon_background_color: "#2563EB"
    icon_background_color_dark: "#0B1F4B"

  # Optional layout tweaks
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
